name: demo_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  bloc_base_architecture:
    git:
      url: https://github.com/sagarkudecha223/bloc_base_architecture.git
      ref: development

  cupertino_icons: 1.0.8
  built_value: 8.11.0
  get_it: 8.2.0
  injectable: 2.5.1
  gap:
  flutter_svg: 2.0.10+1
  flutter_styled_toast:
  shared_preferences: 2.5.3
  firebase_core: 3.0.0
  firebase_auth: 5.0.0
  google_sign_in: 6.2.1
  firebase_database: 11.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: 2.6.0
  built_value_generator: 8.11.0
  injectable_generator: 2.8.1

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins.ttf
