name: demo_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  bloc_base_architecture:
    git:
      url: https://github.com/sagarkudecha223/bloc_base_architecture.git
      ref: development

  cupertino_icons: 1.0.8
  built_value: ^8.11.1
  get_it: 8.2.0
  injectable: 2.5.1
  gap:
  flutter_svg: 2.2.0
  flutter_styled_toast:
  shared_preferences: 2.5.3
  firebase_core: 4.0.0
  firebase_auth: 6.0.1
  google_sign_in: 6.3.0
  firebase_database: 12.0.0
  cached_network_image: 3.4.1
  lazy_load_indexed_stack: 1.1.0
  flutter_animate: 4.5.2
  geolocator: 14.0.2
  flutter_map: 8.2.1
  latlong2: 0.9.1
  permission_handler: 12.0.0+1
  google_maps_flutter: 2.12.3
  flutter_dotenv: 6.0.0
  flutter_polyline_points: 2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: 5.0.0
  build_runner: 2.6.0
  built_value_generator: 8.11.1
  injectable_generator: 2.8.1

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - .env

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins.ttf
