// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCybaNLlYwYl06OizXAQhG3-uwd0tb7TKI',
    appId: '1:848317712616:web:1b404cc38bd40e2d92a15d',
    messagingSenderId: '848317712616',
    projectId: 'e-commerce-app-338db',
    authDomain: 'e-commerce-app-338db.firebaseapp.com',
    databaseURL: 'https://e-commerce-app-338db-default-rtdb.firebaseio.com',
    storageBucket: 'e-commerce-app-338db.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdMllGZK78j-BjJfLEghPfdcPDErEki9A',
    appId: '1:848317712616:android:9d9fdbe9520352c892a15d',
    messagingSenderId: '848317712616',
    projectId: 'e-commerce-app-338db',
    databaseURL: 'https://e-commerce-app-338db-default-rtdb.firebaseio.com',
    storageBucket: 'e-commerce-app-338db.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcdjVMAEIfAsI8gqWUCT2e8x_t1174wtk',
    appId: '1:848317712616:ios:0c7ac60768395e3092a15d',
    messagingSenderId: '848317712616',
    projectId: 'e-commerce-app-338db',
    databaseURL: 'https://e-commerce-app-338db-default-rtdb.firebaseio.com',
    storageBucket: 'e-commerce-app-338db.firebasestorage.app',
    androidClientId:
        '848317712616-g4idmbafh7ip034p9v5e9bgn3uu1q8t6.apps.googleusercontent.com',
    iosClientId:
        '848317712616-hif04gjcdmhn7p0kmas2um61mgap1pfb.apps.googleusercontent.com',
    iosBundleId: 'com.example.demoApp',
  );
}
